### PR TITLE
fix: skip write body when status not allowed

### LINKED ISSUE #788: 2023/05/19 20:21:07.463055 server.go:1928: [Error] HERTZ: HTTP2: write response body error when serving 123.123.123.123:63047: http: request method or response status code does not allow body
**Describe the bug**

@li-jin-gou @Duslia @rogerogers 
```
2023/05/19 20:21:07.463055 server.go:1928: [Error] HERTZ: HTTP2: write response body error when serving 123.123.123.123:63047: http: request method or response status code does not allow body
```

cannot set "consts.StatusNotModified" because in server.go of github.com/hertz-contrib/http2/server.go
line 1922 gives 1928 error if ctx Status return code is 304 notmodified 

pls fix this github.com/hertz-contrib/http2/server.go
it is writeResponseBody() that is giving the error, see comment after line.

server.go file
```
                rw.WriteHeader(reqCtx.Response.StatusCode())
                err = writeResponseBody(rw, reqCtx) //SET BODY HERE WILL ERROR FOR status 304 etc! 
                //those without bodies! BUT... come to think of it, 
                //it should be OK to have custom body for any status. 
                //so i think should fix the code internal.
```
using h2 and latest hertz.

**To Reproduce**
```
func CtxStatusNotModified(ctx *app.RequestContext) {
	ctx.SetStatusCode(consts.StatusNotModified)
	//with or without below line doesnt work
	//ctx.Response.Header.Set("Cache-Control", "no-transform") 
}
```

closed https://github.com/cloudwego/hertz/issues/786 to re-opened here.
**Expected behavior**

no errors

**Screenshots**

**Hertz version:**
0.6

### PR DESCRIPTION
**Pull request by rogerogers**
#### What type of PR is this?

fix

#### What this PR does / why we need it (English/Chinese):

en: don't write body when status not allowed.  According to the RFC definition https://www.rfc-editor.org/rfc/rfc9110.html#name-204-no-content, 204 and 304 response is terminated by the end of the header section; it cannot contain content or trailers.
zh: 状态码不允许存在body的时候不写入body。根据rfc定义，204、304还有其他几个状态码，不能设置响应body，这里跳过写入body。

#### Which issue(s) this PR fixes:

Fixes https://github.com/cloudwego/hertz/issues/788

### CODE REVIEW

**Comment by kolinfluence** [comment]
@rogerogers it's not just status not modified. 
possible to reference this?
https://stackoverflow.com/questions/8628725/comprehensive-list-of-http-status-codes-that-dont-include-a-response-body

also, it's "ok" to include body for custom status code. so i think it's ok to have body everywhere too.

**Comment by rogerogers** [comment]
https://cs.opensource.google/go/x/net/+/master:http2/http2.go;l=304
This is just a solution for this scenario. Writing a body to a status code that does not allow a body will cause the error.

**Comment by rogerogers** [comment]
> @rogerogers it's not just status not modified. possible to reference this? https://stackoverflow.com/questions/8628725/comprehensive-list-of-http-status-codes-that-dont-include-a-response-body
> 
> also, it's "ok" to include body for custom status code. so i think it's ok to have body everywhere too.

This answer is not for http2.

**Comment by kolinfluence** [comment]
possible to expedite this merge?

**Review by kolinfluence — APPROVED** [review]
looks good to me

**Comment by rogerogers** [comment]
cc @wzekin

File: server.go [hunk 1]
```diff
@@ -1854,6 +1854,9 @@ func (sc *serverConn) newWriterAndRequestNoBody(st *stream) (*responseWriter, er
 }
 
 func writeResponseBody(rw *responseWriter, reqCtx *app.RequestContext) (err error) {
+	if !bodyAllowedForStatus(reqCtx.Response.StatusCode()) {
```
Comment (welkeyever) [inline server.go:1857]: There exists a scenario: if users really set a body with these status codes and they will not get any error from that and no body will be sent - which is a different way of process compare to the standard lib?

Comment (rogerogers) [reply server.go:1857]: rfc 也定义了 204和304 https://www.rfc-editor.org/rfc/rfc9110.html#name-204-no-content  不能包含body，即便设置了body也会被忽略。代理比如nginx也会忽略掉body部分，所以设置并没有太大意义。

Comment (kolinfluence) [reply server.go:1857]: @rogerogers is correct, BUT actually i prefer letting the body set because most customized http servers allow so and customized versions of client also will allow so.

but i can live with the rfc standard.

@welkeyever, can you allow the pr for now and think later because not allowing the pull requests is worst than everything else you can think of for now.

we can discuss this AFTER implementation because right now, just setting 304 crashes.

**Review by kolinfluence — APPROVED** [review]
pls just approve else 304 just crash. worst by doing nothing

File: server.go (hunk 1 above)
Comment (welkeyever) [reply server.go:1857]: @rogerogers I think both are ok - if you give a reasonable reason for this change. 
Can you add this part of the change to the description of the pr？

**Review by welkeyever — APPROVED** [review]

File: server.go (hunk 1 above)
Comment (rogerogers) [reply server.go:1857]: done.

**Comment by kolinfluence** [comment]
@rogerogers @welkeyever 
pls update the release version too. thx

**Comment by rogerogers** [comment]
> @rogerogers @welkeyever pls update the release version too. thx

You can use github.com/hertz-contrib/http2@962a08ada7d76a386c4b47a7d65cf75d0275c291 to perform your test. and update it when we release the new version
